### ISSUE TITLE
Inconsistent screen unlock behavior

### ISSUE THREAD

**Issue by HankAviator** [darkeyes84/dark_tricks#4]
Hello, recently I noticed Dark tricks is preventing my device from being woken up normally. DT2W and power button both fail to wake up the screen sometimes. When it happens, logcat gives
```
01-10 00:02:00.844  1746  2307 D WindowManager: powerPress: eventTime=620353 interactive=false count=1 beganFromNonInteractive=true mShortPressOnPowerBehavior=1
01-10 00:02:00.845  1746  2707 V InputDispatcher: Asynchronous input event injection succeeded.
```
despite I have turned off 'prevent accidental wake up' both in dark tricks, and in system settings. I have enabled 'hide vpn notifications' and 'hide build version' in dark tricks.

I've tried to uninstall, reinstall dark tricks, edxposed, riru, rebooting. This does not happen when i disable dark tricks. I guess it's most likely to be caused by 'prevent accidental wake up' in dark tricks.

Dark trick version: 2.11
System: LineageOS 17.1 (Android 10)
Magisk: 21.2
Edxposed: 93-v0.5.1.3_4646 sandhook
Riru: v23.1

Update: version 2.3 works well since 'check proximity before wake up' wasn't introduced yet.

**Comment by HankAviator** [comment]
2.3 hides alarm icon and in some cases may prevent alarm UI from showing, should have been fixed in later releases.

**Comment by darkeyes84** [comment]
Update to the latest v2.12 and report back. I didn't fix your problem, but you should be able to disable proximity wake up properly now.
